### ISSUE TITLE
Segfaults when offsetting polygon

### ISSUE THREAD

**Issue by bellwether-softworks** [lelongg/clipper-sys#21]
OS: Windows 10 x64

I'm attempting to offset a polygon, and am receiving a segfault when doing so.  If LLDB is to be trusted, I believe this is due to `size_t` not mapping correctly; looking at [bindings.rs](https://github.com/lelongg/clipper-sys/blob/master/generated/bindings.rs#L3), `size_t` ultimately resolves to [`u32`](https://doc.rust-lang.org/std/os/raw/type.c_ulong.html), whereas in C++ the `size_t` is considered `u64` (unsigned long long):

![image](https://user-images.githubusercontent.com/66568249/141468516-e5db6f3d-ef9e-4fe1-b038-b6d422bed323.png)

![image](https://user-images.githubusercontent.com/66568249/141468558-d2e836f3-e7cb-4bf4-87cf-5198b46b083c.png)

The failure is occurring [here](https://github.com/lelongg/clipper-sys/blob/master/clipper/wrapper.cpp#L33), I believe due to inflated count values as indicated in the second screenshot.  This issue does not present when the same application is run in Linux.

**Comment by lelongg** [comment]
Does the size_t branch fix your issue ?

**Comment by bellwether-softworks** [comment]
It does, thank you for addressing this so quickly.
