### ISSUE TITLE
Difference with Wagyu clipping lib

### ISSUE THREAD

**Issue by nyurik** [lelongg/clipper-sys#23]
Hi, I noticed your lib wraps Angus Johnson clipping lib (unchanged since 2014?), and that seems to be the same lib that was used as the basis of [Mapbox's wagyu](https://github.com/mapbox/wagyu). Moreover, Postgis has switched to Wagyu for their clipping needs as well. Would it make sense to migrate to Wagyu as it is far more recent and maintained?  I am trying to re-implement some Postgis-based code in Rust, and clipping is a big part of that.  Thanks!

**Comment by lelongg** [comment]
Yes I suppose we could even have both wrapped inside this crate behind feature gates, PR welcome

**Comment by nyurik** [comment]
Thx @lelongg !  Would you be interested in moving this crate to the https://github.com/georust so that there is a bigger community working on it?

**Comment by lelongg** [comment]
yes totally

**Comment by nyurik** [comment]
Thanks!  I wonder if we should merge the `clipper-sys` and `geoclipper` into a single repo, perhaps as two workspaces/subdirs, so that they are more in-sync with each other, and make it easier to validate the whole package in CI. I have asked the community about it as well - https://discord.com/channels/598002550221963289/598002550221963291/951190737570127915

**Comment by lelongg** [comment]
I don't know if there is any downside with this but it's ok with me

**Comment by nyurik** [comment]
ok, i will sync with the core maintainers of the georust, and will post the response here so we can start the transfer (key people will need to be added to the crates so that it can be published by more people). Thx again!
